<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBx0CfOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBx0CfOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBx0CfOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBx0CfOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBx0CfOx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bx0CfOx',
    'container.build_id' => '5016ac4f',
    'container.build_time' => 1604259481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBx0CfOx');
