<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCC5ZnTU\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCC5ZnTU/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCC5ZnTU.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCC5ZnTU\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCC5ZnTU\App_KernelProdContainer([
    'container.build_hash' => 'CC5ZnTU',
    'container.build_id' => 'e5c951ce',
    'container.build_time' => 1601026833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCC5ZnTU');
