<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'blog-index' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/blog/']], [], []],
    'blog-add' => [[], ['_controller' => 'App\\Controller\\BlogController::add'], [], [['text', '/blog/add']], [], []],
    'blog-show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog/show']], [], []],
    'following_follow' => [['id'], ['_controller' => 'App\\Controller\\FollowingController::follow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/following/follow']], [], []],
    'following_unfollow' => [['id'], ['_controller' => 'App\\Controller\\FollowingController::unfolow'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/following/unfollow']], [], []],
    'likes_like' => [['id'], ['_controller' => 'App\\Controller\\LikesController::like'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/likes/like']], [], []],
    'likes_unlike' => [['id'], ['_controller' => 'App\\Controller\\LikesController::unlike'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/likes/unlike']], [], []],
    'micro_post_index' => [[], ['_controller' => 'App\\Controller\\MicroPostController::index'], [], [['text', '/micro-post/']], [], []],
    'micro_post_add' => [[], ['_controller' => 'App\\Controller\\MicroPostController::add'], [], [['text', '/micro-post/add']], [], []],
    'micro_post_edit' => [['id'], ['_controller' => 'App\\Controller\\MicroPostController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/micro-post/edit']], [], []],
    'micro_post_delete' => [['id'], ['_controller' => 'App\\Controller\\MicroPostController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/micro-post/delete']], [], []],
    'micro_post_user' => [['username'], ['_controller' => 'App\\Controller\\MicroPostController::userPosts'], [], [['variable', '/', '[^/]++', 'username', true], ['text', '/micro-post/user']], [], []],
    'micro_post_post' => [['id'], ['_controller' => 'App\\Controller\\MicroPostController::post'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/micro-post']], [], []],
    'notification_unread' => [[], ['_controller' => 'App\\Controller\\NotificationController::unreadCount'], [], [['text', '/notification/unread-count']], [], []],
    'notification_all' => [[], ['_controller' => 'App\\Controller\\NotificationController::notifications'], [], [['text', '/notification/all']], [], []],
    'notification_acknowledge' => [['id'], ['_controller' => 'App\\Controller\\NotificationController::acknowledge'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/notification/acnowledge']], [], []],
    'notification_acknowledge_all' => [[], ['_controller' => 'App\\Controller\\NotificationController::acknoledgeAll'], [], [['text', '/notification/acnowledge-all']], [], []],
    'user_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/register']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'security_confirm' => [['token'], ['_controller' => 'App\\Controller\\SecurityController::confirm'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/confirm']], [], []],
];
